# Generated by Django 4.2.7 on 2023-11-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mbti',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
