# Generated by Django 4.2.7 on 2023-11-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_mbti"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="android",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="backEnd",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="frontEnd",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ios",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phoneNum",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="uiux",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="web",
            field=models.BooleanField(null=True),
        ),
    ]
