# Generated by Django 4.2.7 on 2023-11-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_kakao_alter_spec_spec"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spec1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spec2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spec3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spec4",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Spec",
        ),
    ]
