# Generated by Django 4.2.7 on 2023-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_spec1_user_spec2_user_spec3_user_spec4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao',
            field=models.URLField(blank=True, null=True),
        ),
    ]
